# Generated by Django 4.0.5 on 2022-07-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vino',
            name='cosecha_anual_kgs',
        ),
    ]
